### ISSUE TITLE
Add upload image page

### ISSUE THREAD

**Issue by jamiejcole** [tobsterclark/Xeon-Photography#6]
Needs to:
* Require Google Account authentication with Firebase Auth
* Automatically compress images with **medium** and **large** sizes
* Place images into Firebase Hosting

**Comment by jamiejcole** [comment]
**Added:**
- Styled dropzone and upload button

**Need to add:**
- Responsiveness, indicating failed/successful uploads
- Indicator for amount of files
- Login auth

**Comment by tobsterclark** [comment]
**Added:**
- responsive uploading
- compression
- indicator for amount of files
**Need to add: **
- Login Auth
- Access from main page

**Comment by tobsterclark** [comment]
All features completed 👍
